#!/bin/sh
#  -*- sh -*-

: << =cut

=head1 NAME

bash_hist_ - Count bash_history lines

=head1 CONFIGURATION

It is a wildcard plugin, symlink it into the plugins directory.

Through environment:
  bash_hist_warning=<warning-level> # or
  warning=<warning-level>
  bash_hist_critical=<critical-level> # or
  critical=<critical-level>

When running under SystemD, this requires 'ProtectHome=read-only' in the unit.
(But that does seem to break munin-run when put into an override file.)

=head1 AUTHOR

Unknown author

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

user_name=$( basename "$0" | cut -c11- )

. "$MUNIN_LIBDIR/plugins/plugin.sh"

case "${1:-print}" in

  ( autoconf )
      if [ -e /home/$user_name/.bash_history -a -r /home/$user_name/.bash_history ]; then
        echo yes
        exit 0
      else
        echo no
        exit 0
      fi
    ;;

  ( config )
      if [ "$1" = "config" ]; then
        echo 'graph_title User command history'
        echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel commands (lines)'
        echo 'graph_scale no'
        echo 'graph_category system'
        #echo 'graph_info This graph shows '
        echo "bash_hist_$user_name.label bash-hist for $user_name"
        #echo 'bash_hist.info more info.'
        print_warning bash_hist
        print_critical bash_hist
        exit 0
      fi
    ;;

  ( print|update|fetch )
      echo -n "bash_hist_$user_name.value "
      grep -v '^#' /home/$user_name/.bash_history | wc -l | cut -d ' ' -f 1
    ;;

esac
